### ISSUE TITLE
from ip_adapter.attention_processor import IPAttnProcessor2_0 ModuleNotFoundError: No module named 'ip_adapter'

### ISSUE THREAD

**Issue by guahunyo** [smthemex/ComfyUI_StoryDiffusion#1]
![I F5LVINOLGW~ MU7XN~_4V](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/18573180/87f19a43-950c-4164-8819-91db41e492e6)

**Comment by smthemex** [comment]
pip install -r requirements.txt --target="your path\python_embeded\Lib\site-packages"  or pip install -r requirements.txt

**Comment by smthemex** [comment]
and update this node ，i fix some bug

**Comment by guahunyo** [comment]
> and update this node ，i fix some bug并更新此节点，我修复了一些错误

![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/18573180/5c1e98b4-3daa-412a-aee9-40f76a6ede5f)
Now the workflow can be established normally, but there are still problems during operation.

**Comment by smthemex** [comment]
默认的如果juggemaut模型，连接的是C站的模型地址，你可以打开comfig文件夹下，的model.yaml文件，把第一排juggemaut的下path：后面的C站地址改成你的本地模型地址。或者你用其他的模型。用juggemaut默认是要联外网下载的

**Comment by guahunyo** [comment]
> 默认的如果juggemaut模型，连接的是C站的模型地址，你可以打开comfig文件夹下，的model.yaml文件，把第一排juggemaut的下path：后面的C站地址改成你的本地模型地址。或者你用其他的模型。用juggemaut默认是要联外网下载的

The screenshot above is the result after I changed it.
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/18573180/d449ae73-341b-4eba-80e1-aceae970900a)

**Comment by smthemex** [comment]
本地模型的地址要改成/，也就是C:/XXX/XX，而且只有第一个jug才支持单模型，但是也要下载该模型的config文件到模型目录，下面3个都必须填写标准的repo_id（插件默认的内容），或者该repo_id的本地绝对路径。比如 c:/XXX/XXX/stabilityai/stable-diffusion-xl-base-1.0
