### ISSUE TITLE
双角色的相关

### ISSUE THREAD

**Issue by oyw233** [smthemex/ComfyUI_StoryDiffusion#103]
感谢您的工作，对我很有用，不过有几个疑问点想问一下，看官方的story diffusion支持双角色且相互不污染，想问一下这个能够支持storydiffusion的双角色生成吗，因为我看了一下代码，两个角色同框应该是基于ms diffusion来做的，先文生图，再将生的图来做ms diffusion。

**Comment by oyw233** [comment]
@smthemex 好哒，谢谢，还想问个问题，就是发现双角色同框的时候，当生成多个角色的时候角色位置都是处于比较一致的状态

**Comment by smthemex** [comment]
如果使用MS，可以自定义调整角色的位置，sampler最下面那两组数据，代表角色的在画面的方框位置，如果2组数字一样，2个人物就是重叠的，第一组数字是第一个角色，上下左右，就要你自己来调整了。除此之外，prompt里位置信息也很关键，你要角色在左右上下，最好是写出来，比如在画面中央一类。
而story-maker用的是蒙版，但是双人的蒙版也是用单人的合并，没有自定义，完全要靠prompt

**Comment by oyw233** [comment]
@smthemex 好的哈，那如果我要连续生成多张合体图像，我是不是需要把下边那串数字删除，然后完全通过prompt来控制角色位置相关

**Comment by smthemex** [comment]
你把 mask_threshold 设置为0就好，0就是不使用自定义

**Comment by oyw233** [comment]
@smthemex 好的哈，谢谢啦
