### ISSUE TITLE
storydiffusion模型一致性效果相关

### ISSUE THREAD

**Issue by oyw233** [smthemex/ComfyUI_StoryDiffusion#104]
你好，请问一下这里有参数可以调整一致性嘛，感觉有的时候好像一致性不是很好的样子

**Comment by oyw233** [comment]
![image](https://github.com/user-attachments/assets/44d4046b-9bea-4897-851d-1be9f7dfc756)
大概是这个效果，感觉一致性好像不怎么好

**Comment by smthemex** [comment]
动物有点难，因为基本上内置的都是抓人脸的。

**Comment by oyw233** [comment]
> 动物有点难，因为基本上内置的都是抓人脸的。

是啊，我也是看见内置了很多模型都是基于人脸的
