### ISSUE TITLE
缺少节点类型 加载图形时，未找到以下节点类型Storydiffusion_Text2Img

### ISSUE THREAD

**Issue by czm0208** [smthemex/ComfyUI_StoryDiffusion#117]
缺少节点类型
加载图形时，未找到以下节点类型Storydiffusion_Text2Img，这是为什么呢？

**Comment by smthemex** [comment]
你的工作流是旧的

**Comment by czm0208** [comment]
哦，解决了，我看了您在B站的回复，解决了。谢谢大佬

**Comment by Daqi-aaa** [comment]
> 哦，解决了，我看了您在B站的回复，解决了。谢谢大佬

请问下怎么解决的，新的工作流在哪里呢？

**Comment by Daqi-aaa** [comment]
> 你的工作流是旧的

新的工作流在哪里呢
