### ISSUE TITLE
大佬，两个问题哈。

### ISSUE THREAD

**Issue by ffhelly** [smthemex/ComfyUI_StoryDiffusion#12]
在选择单一 sdxl模式   偶尔会抽风去下载  sdxl的模型。。 什么都不动的情况下。

第二个是   现在是单一标签对应角色。  如果一张图需要  2个或2个以上 该如何标记这张图呢？

我试过 [A,B]   或者  [A] [B]  都无法实现该需求。

**Comment by smthemex** [comment]
有些模型可能训练的时候weight 有缺失，所以要下载，或者是clip文件，这个我正在优化。
单图双角色目前有计划做，如果官方没有更新，我就内置进去。
