### ISSUE TITLE
建议img-style变成 string输入

### ISSUE THREAD

**Issue by xueqing0622** [smthemex/ComfyUI_StoryDiffusion#14]
img-style不是太稳定，权重不可控
建议img-style变成 string输入，可以自己连入自己写的或者一些其他预制的风格提示词
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/114840118/7901e833-97a7-4d3f-b6c6-2cf6d6c3ddb3)

**Comment by smthemex** [comment]
我回头改一下吧，这里一直没空动。

**Comment by xueqing0622** [comment]
> 我回头改一下吧，这里一直没空动。

嗯 只是提一嘴
