### ISSUE TITLE
autoStudio是否更稳定一点 对于角色

### ISSUE THREAD

**Issue by xueqing0622** [smthemex/ComfyUI_StoryDiffusion#15]
autoStudio是否更稳定一点 对于角色
不过可惜只有1.5
https://github.com/donahowe/AutoStudio

**Comment by smthemex** [comment]
双角色表现的确不错，没人移植的话，我就把它也移植到comfyUI来

**Comment by xueqing0622** [comment]
是的 1.5都很稳定 期待XL效果更好

**Comment by FLYleoYBQ** [comment]
The XL version came out today. Is the big guy free to transplant? Really look forward to some, my code ability is strong on their own transplantation, haha
