### ISSUE TITLE
"lora_scale" does not affect the output

### ISSUE THREAD

**Issue by vi-sa-vie** [smthemex/ComfyUI_StoryDiffusion#16]
First of all, thank you for the wonderful custom node!

Adding loras is a great feature, but unfortunately the "lora_scale" value does not seem to be affecting the output. See the attached image for reference:

![Image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/138396869/f6f536dd-b3ef-4e0f-ae3f-501c356cd435)

I did take a look at the code, and the `cross_attention_kwargs={"scale": lora_scale}` does seem correct after some investigation, but I don't know enough to say if something else is missing.

I thought xformers could be the issue, but the result is same even after uninstalling it.

ComfyUI: 2258\[922e7c](2024-06-15) Portable
torch: 2.3.1+cu121
transformers: 4.41.2

**Comment by smthemex** [comment]
I will check the code, thank you

**Comment by vi-sa-vie** [comment]
After pulling the latest commits, the lora_scale value seems to work now, thank you.
