### ISSUE TITLE
建议拉出model和conditioning节点。支持controlnet和ipadapter

### ISSUE THREAD

**Issue by xueqing0622** [smthemex/ComfyUI_StoryDiffusion#17]
建议拉出model和conditioning节点。支持controlnet和ipadapter，这样可控性更高

**Comment by smthemex** [comment]
模型加载和采样分开做节点是有这个计划，不过我最近有点忙，迟点吧。controlnet则工作量更大，因为要可控每张图的condition，虽然已有思路，但是要大改代码，也只能押后再做了。

**Comment by xueqing0622** [comment]
ok， 我只是这么一说。
你B站说双人同框做好了， 放出来没有！

**Comment by xueqing0622** [comment]
哈哈，去b站看到上线了。下来玩玩。
不能支持多lora，先自己融到大模型里。

**Comment by smthemex** [comment]
双lora节点迟点做吧，等我忙完这段时间

**Comment by xueqing0622** [comment]
辛苦了 不急的
