### ISSUE TITLE
 in process_generation raise 'Please add the triger word " img " behind the class word you want to customize, such as: man img or woman img'

### ISSUE THREAD

**Issue by Agnyy** [smthemex/ComfyUI_StoryDiffusion#20]
Я уже несколько раз запустил генерацию, но ещё не разу не сгенерировался нужный результат. Почему то всё время выдаёт эту ошибку, где и как именно это исправлять не понятно.

It gives an error, it didn’t show it before, how can I fix it now?

"in process_generation
raise 'Please add the triger word " img " behind the class word you want to customize, such as: man img or woman img'"

![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/25137502/0b1182fb-b8dd-4f05-acb8-24ddcf810a5a)
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/25137502/960fa117-0fae-46db-87ba-1b2e0fdeda14)

**Comment by smthemex** [comment]
if you using txt2img,model_type need choice origin,    I  will remove this confusing menu in the next update

**Comment by Agnyy** [comment]
Спасибо большое ! 
Thank you!
