### ISSUE TITLE
photomaker

### ISSUE THREAD

**Issue by Unclesimonlau** [smthemex/ComfyUI_StoryDiffusion#21]
photomaker_dir = os.path.join(dir_path, "weights")
        photomaker_local_path = os.path.join(photomaker_dir, "photomaker-v1.bin")

        if model_type == "img2img":
            if not os.path.exists(photomaker_local_path):
                photomaker_path = hf_hub_download(
                    repo_id="TencentARC/PhotoMaker",
                    filename="photomaker-v1.bin",
                    repo_type="model",
                    local_dir=photomaker_dir,
                )
            else:
                photomaker_path = photomaker_local_path
            photomaker_path=get_instance_path(photomaker_path)
这里是不是应该是
if model_type == "text2img":

**Comment by Unclesimonlau** [comment]
不对txt2img

**Comment by smthemex** [comment]
不是，这里就不该加这个判断的，我最后的更新去掉了
