### ISSUE TITLE
Error when changing 3 words in example workflow : Error occurred when executing KSampler:  shape '[2, -1, 640]' is invalid for input of size 3976320

### ISSUE THREAD

**Issue by piovis2023** [smthemex/ComfyUI_StoryDiffusion#25]
Hi

Can anyone help. 

The example workflow from this repo (cute girl, red hair..) works perfectly when I changed the checkpoint to Juggernaught XL.

Then when I changed ONLY the prompt to "a cute girl, 26-year old, mexican, dirty brown hair, skinny" (only a few words different), I get this error: 

"Error occurred when executing KSampler:

shape '[2, -1, 640]' is invalid for input of size 3976320"

Remember - I haven't changed anything else?

I've tried less words and still the same error, but with different numbers. 

Can anyone help?

**Comment by smthemex** [comment]
Are you running in the dual role mode of txt2img? Currently, there is a bug in this mode and it does not support repeated use of pipes. If you want to use it again, you must change any parameters of the model loading node, such as the scheduler.
If there are other causes of errors, in the character prompt, there are" \n "line breaks after the punctuation (comfyUI cannot display). If the punctuation is removed when changing the character prompt, it may cause an error in the input tensor. To avoid this error, try not to remove the punctuation in the example or use the "split prompt" function
