### ISSUE TITLE
Error occurred when executing Storydiffusion_Sampler:  exceptions must derive from BaseException :: Img2Img

### ISSUE THREAD

**Issue by piovis2023** [smthemex/ComfyUI_StoryDiffusion#26]
Trying the img2img workflow from the repo with minimal changes.

Can someone please help and educate me? Thank you

Error:
Error occurred when executing Storydiffusion_Sampler:
exceptions must derive from BaseException
...

raise f"{character_key} not have enough prompt description, need no less than {id_length}, but you give {len(index_list)}"

<img width="997" alt="image" src="https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/130514657/957dc6e3-9b65-4412-b389-5a162b336a21">

**Comment by smthemex** [comment]
In the scene prompt, each character's prompt needs to appear separately at least twice ，in  this issues ，Rose needs to appear twice in the scene_ prompts .

**Comment by smthemex** [comment]
I have noticed another error in your workflow. If you want to use "encode-repo", you need to change your address from C:\xxx\xxx to C:/xxx/xxx. If you have already downloaded using the preset huggingface_hub, this address can be kept as the default "laion/CLIP ViT bigG-14 laion2B-39B-b160k". Modifying this here is only for the convenience of those who prefer to use the local model, or whose huggingface_hub cache address is not on the default C: drive

**Comment by piovis2023** [comment]
Thanks @smthemex for the very quick reply.

EXCELLENT work and EXCELLENT support.

Here is my corrected workflow (thanks to you):
<img width="1007" alt="image" src="https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/130514657/a50e4b9b-3475-45d6-a27f-17d4099d0b00">


A few additional queries (I can raise new tickets for each if that is useful to you)
1. How can we put 2+ characters in the same scene? (I tried to copy your workflow example image). I get the following error:
Error occurred when executing Storydiffusion_Sampler:
list index out of range

2. How can we control camera distance? e.g. far away shot
3. How can we improve the closeness of the character?
4. Can we include other background characters in the background scene? (e.g a crowd cheering)
5. Do you have a workflow the includes both text to image and img2img? I'd be curious to have temporary characters in my comic without having to supply all characters.  (e.g. a close up of a waiter dropping a glass in front of Rose)

**Comment by smthemex** [comment]
Currently, only two characters are supported in the same image. To enable this feature, (roleA and roleB) is required. The lens perspective function can only be improved by prompt, such as "media shot". If you want to enable certain special perspectives, you may need to introduce a control net reference image. Of course, the control net function is only suitable for scenes where "two characters are in the same image", and the original method for single character scenes was not provided.
Perhaps you can try another similar story node I created based on MS diffusion, which supports full scene controlnet.
I noticed that my sample images are all older, and I will update the image examples and corresponding workflows soon.

**Comment by drawart** [comment]
Hi, I have the same Error:
Error occurred when executing Storydiffusion_Sampler:
exceptions must derive from BaseException

Workflow:
![Image](https://github.com/user-attachments/assets/eb2bb78d-b993-4239-aadb-251773fadc50)

When I make 4 images it is working fine, but when I try to make 5 images or image with two characters, there is this error.

Could you advise, please, how to fix it?

**Comment by smthemex** [comment]
> Hi, I have the same Error: Error occurred when executing Storydiffusion_Sampler: exceptions must derive from BaseException
> 
> Workflow: ![Image](https://github.com/user-attachments/assets/eb2bb78d-b993-4239-aadb-251773fadc50)
> 
> When I make 4 images it is working fine, but when I try to make 5 images or image with two characters, there is this error.
> 
> Could you advise, please, how to fix it?

flux don't support dual characters now，>4 image get error maybe a bug
