### ISSUE TITLE
安装完直接连节点都找不到。。

### ISSUE THREAD

**Issue by sufaming** [smthemex/ComfyUI_StoryDiffusion#27]
装了这么多插件，你这个还是第一次遇到，老哥是不是又整出啥新bug了？

**Comment by smthemex** [comment]
因为内置了MS-diffusion，所以要求diffuser大于0.28以上，装不上大部分是这个原因。IP-adapter我都已经内置了

**Comment by sufaming** [comment]
的确，就是依赖没全，调试了下，最后全部手动安装就行了......理论上讲不应该直接在 requirements.txt 都写全的吗
