### ISSUE TITLE
大模型地址错误

### ISSUE THREAD

**Issue by lancje** [smthemex/ComfyUI_StoryDiffusion#3]
Error occurred when executing Storydiffusion_Text2Img:

Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory F:\123\HF_HOME\hub\models--stabilityai--stable-diffusion-xl-base-1.0\snapshots\462165984030d82259a11f4367a4eed129e94a7b\text_encoder.
在修改model里面的指定的目录下找到这个具体的文件。
Juggernaut:
  path: ""F:\sd-webui-aki\sd-webui-aki-v4.1\models\Stable-diffusion\Juggernaut_X_RunDiffusion_Hyper.safetensors""
  single_files: true
  use_safetensors: true，
说明修改错误吧？请解惑

**Comment by smthemex** [comment]
地址请改成 F:/sd-webui-aki/sd-webui-aki-v4.1/models/Stable-diffusion/Juggernaut_X_RunDiffusion_Hyper.safetensors ，并去掉引号

**Comment by lancje** [comment]
已解决，感谢
