### ISSUE TITLE
ImportError: cannot import name 'IPAdapterMaskProcessor' from 'diffusers.image_processor' (D:\ComfyUI-aki-v1.2_T8\python\lib\site-packages\diffusers\image_processor.py)

### ISSUE THREAD

**Issue by T8star1984** [smthemex/ComfyUI_StoryDiffusion#31]
ImportError: cannot import name 'IPAdapterMaskProcessor' from 'diffusers.image_processor' (D:\ComfyUI-aki-v1.2_T8\python\lib\site-packages\diffusers\image_processor.py)

**Comment by smthemex** [comment]
when using MS -diffusion ，need diffusers>0.28.0，i will change the requirements.txt

**Comment by smthemex** [comment]
sorry  it's a no using code,i  will delete it..
