### ISSUE TITLE
为什么不用comfy内置的load checkpoints加载sd模型，而是在Storydiffusion_Model_Loader里配置模型加载

### ISSUE THREAD

**Issue by eastoc** [smthemex/ComfyUI_StoryDiffusion#32]
这种设计和其他node不一样，从开发和使用角度来说都变得更麻烦

**Comment by smthemex** [comment]
因为2个方法都魔改了pipe流程，所以走comfyUI内置的，可能跑不通，要么修改方法，这样太耗时了。我没空整。

**Comment by eastoc** [comment]
> 因为2个方法都魔改了pipe流程，所以走comfyUI内置的，可能跑不通，要么修改方法，这样太耗时了。我没空整。

我去改了下，确实是个费时间的活
