### ISSUE TITLE
local_diffuser没有设置成无的选项。。。

### ISSUE THREAD

**Issue by lanse6899** [smthemex/ComfyUI_StoryDiffusion#33]
local_diffuser这里没有设置成无的选项。
![微信截图_20240711105313](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/167429044/7e8a502d-073e-4122-9d41-5cc518cc393c)

**Comment by smthemex** [comment]
默认就是无，但是如果你的comfyUI连diffuser文件夹都没有，就会报错，你建一个空的就有无了。

**Comment by lanse6899** [comment]
是在models下创建一个空的diffuser文件夹吗。创建了依然没有无找个选项

**Comment by lanse6899** [comment]
![微信截图_20240711151448](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/167429044/148e6559-4e71-4cfe-a73e-85d7fc7b8997)

**Comment by paofather** [comment]
我原先有个diffusers的文件夹，但是选项只有一个，
![微信截图_20240711174054](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/36979714/a876c4f9-7350-4433-a0b3-bdced2cfb483)
然后我新建了一个diffuser的文件夹，
![微信图片_20240711173933](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/36979714/b0cbff0e-559a-4ab1-acf0-9ffd75d4059e)，
选项变成了null，也没有none选项
应该怎么才是正确的？

**Comment by aadian** [comment]
真快，已经可以了，B站一键三连
