### ISSUE TITLE
动不动就torch.cuda.OutOfMemoryError: Allocation on device

### ISSUE THREAD

**Issue by xueqing0622** [smthemex/ComfyUI_StoryDiffusion#36]
ms-diffusion和storydiffusion这两个一加lora
而且非常慢 载入模型
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/114840118/df63a20f-baa5-47bb-a133-ff4c96586cdc)

**Comment by xueqing0622** [comment]
3060 12G   
32G内存

**Comment by xueqing0622** [comment]
好的  谢谢解答

**Comment by YuanXiaoYaoZiZai** [comment]
4090 24G 65G内存，加了controlnet也会报oom

**Comment by smthemex** [comment]
内存溢出是这个方法的老毛病了，原生用他们的方法跑，4090有些也跑不起来，多半是torch或者diffuse这类版本的差异。
