### ISSUE TITLE
关于contrlnet功能，上传的动作参考图片，怎么控制在第几张生成的图片里应用动作？

### ISSUE THREAD

**Issue by huanxve** [smthemex/ComfyUI_StoryDiffusion#39]
关于contrlnet功能，上传的动作参考图片，怎么控制在第几张生成的图片里应用动作？我看工作流里的参考的动作都是双人的，然后生成的图片里也只有一张是双人的，请问怎么控制哪张生成的图片要应用contrlnet？还是说工作流根据提示词自动判断的？

**Comment by smthemex** [comment]
只有双人才用到controlnet，插件自动判断
