### ISSUE TITLE
安装后无法正常启动comfyui

### ISSUE THREAD

**Issue by Tanglinling** [smthemex/ComfyUI_StoryDiffusion#4]
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/146339730/c3f0976a-c84d-4241-8969-7bc3d60ad0c9)

**Comment by smthemex** [comment]
你把插件删掉 再看看能不能启动，然后要你是不是安装了需求文件

**Comment by Tanglinling** [comment]
我卸载这个插件后能正常启动使用了，但是每次通过秋叶的启动器启动都会重新安装一次 onnxruntime-gpu ，因为有一些版本不匹配的原因导致每次都安装失败。所以，我删除了整个文件夹重新部署了秋叶的免安装包。
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/146339730/48918368-40f7-42ef-a11a-6ccf9eb987f0)

**Comment by smthemex** [comment]
你可以反馈下重新部署秋叶包能否用
