### ISSUE TITLE
Error no file named model_index.json found in directory

### ISSUE THREAD

**Issue by Walter-Chan** [smthemex/ComfyUI_StoryDiffusion#40]
请问 为什么一开始运行的时候就跳出这个问题？但是对应文件夹的模型都已经有了。
Error no file named model_index.json found in directory C:\Users\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff.

**Comment by smthemex** [comment]
这是先找的默认C盘的路径，你用的是其他路径的clip吗？如果用其他路径的，把默认的删掉

**Comment by Walter-Chan** [comment]
> 这是先找的默认C盘的路径，你用的是其他路径的clip吗？如果用其他路径的，把默认的删掉
我就存在默认的C盘位置，就是下载的模型没有提到的有这个文件model_index. json
![屏幕截图 2024-07-16 092412](https://github.com/user-attachments/assets/8365714a-e8a7-4007-a16d-904338259d1e)

**Comment by smthemex** [comment]
是加载不了,还是只问题报错,如果能跑通不用管,每个人人的环境不同.
