### ISSUE TITLE
node not working

### ISSUE THREAD

**Issue by raochinmay6** [smthemex/ComfyUI_StoryDiffusion#44]
see below image 
![Screenshot (37)](https://github.com/user-attachments/assets/ab4b0e45-2187-4811-95b9-a6e3deb09d65)

**Comment by raochinmay6** [comment]
When loading the graph, the following node types were not found:
SeaArtAppendPrompt
SeaArtApplyStory
SeaArtMergeStoryCondition
SeaArtCharactorPrompt
Nodes that have failed to load will show as red on the graph.

**Comment by smthemex** [comment]
Did you submit an issue with another node that the “story diffuseion”  doesn't have the nodes shown in your picture。

**Comment by raochinmay6** [comment]
no bro i just dont under stand I am really sorry for that but can you help me out here because a person says this missing node is part of the story diffusion node and I don't understand what to doo

**Comment by smthemex** [comment]
In this case, you only need to use the “manager”（Five o'clock direction） you have installed and use the function of installing missing nodes inside to install it. I'm not sure who gave you advice, that person knows I will help people solve problems in a friendly manner.

**Comment by raochinmay6** [comment]
I'm sorry bro i tried but in manager no missing node showing me

**Comment by raochinmay6** [comment]
i approach you on my own no one advice me bro I just hope that you help me out

**Comment by smthemex** [comment]
https://github.com/SeaArtLab/comfyui_storydiffusion  OK it from a node likes my node....

**Comment by raochinmay6** [comment]
thanks bro thank you very much

**Comment by raochinmay6** [comment]
i hope you will help me in future too 👍 🥇

**Comment by kleio1975** [comment]
<img width="1135" alt="Captura" src="https://github.com/user-attachments/assets/ebb10089-0df9-4145-b822-df56fa2f93ce">
Sorry, I have the same problem, can you explain how to solve it? Please, I swear I have looked everywhere for the solution but I can't find anything.

**Comment by smthemex** [comment]
> <img alt="Captura" width="1135" src="https://private-user-images.githubusercontent.com/59042582/358640461-ebb10089-0df9-4145-b822-df56fa2f93ce.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTU2NjIsIm5iZiI6MTcyMzg1NTM2MiwicGF0aCI6Ii81OTA0MjU4Mi8zNTg2NDA0NjEtZWJiMTAwODktMGRmOS00MTQ1LWI4MjItZGY1NmZhMmY5M2NlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDAwNDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3N2YwYjQwM2IyZTZjMDc3YTAyZTk0MzhkNGQxN2E2YzA2MTJkMTkzNzhjNWFhMmMwYWIwZmVkODM4MzhkZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A29UI8_w8RpxqMIIRDZq0mEgwGNsTREj6qYr_nwvnWs"> Sorry, I have the same problem, can you explain how to solve it? Please, I swear I have looked everywhere for the solution but I can't find anything.

it's not my node,you can find some  in https://github.com/SeaArtLab/comfyui_storydiffusion ，

**Comment by kleio1975** [comment]
> > <img alt="Captura" width="1135" src="https://private-user-images.githubusercontent.com/59042582/358640461-ebb10089-0df9-4145-b822-df56fa2f93ce.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTU2NjIsIm5iZiI6MTcyMzg1NTM2MiwicGF0aCI6Ii81OTA0MjU4Mi8zNTg2NDA0NjEtZWJiMTAwODktMGRmOS00MTQ1LWI4MjItZGY1NmZhMmY5M2NlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDAwNDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3N2YwYjQwM2IyZTZjMDc3YTAyZTk0MzhkNGQxN2E2YzA2MTJkMTkzNzhjNWFhMmMwYWIwZmVkODM4MzhkZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A29UI8_w8RpxqMIIRDZq0mEgwGNsTREj6qYr_nwvnWs">Disculpa tengo el mismo problema, ¿me puedes explicar como solucionarlo? Por favor, te juro que he buscado por todos lados la solución pero no encuentro nada.
> 
> No es mi nodo, puedes encontrar algunos en https://github.com/SeaArtLab/comfyui_storydiffusion，

The link you sent me, could you tell me how I have to add or install them in comfyui?

**Comment by smthemex** [comment]
git clone https://github.com/SeaArtLab/comfyui_storydiffusion.git

**Comment by kleio1975** [comment]
> clon git https://github.com/SeaArtLab/comfyui_storydiffusion.git

But I have to clone it into what folder? from comfyui? inside models? Can you extend the instructions a little more please?

**Comment by smthemex** [comment]
in .. ComfyUI/custom_nodes/   open cmd ,then  git clone...
