### ISSUE TITLE
模型路径方面的问题

### ISSUE THREAD

**Issue by Benbiubiu** [smthemex/ComfyUI_StoryDiffusion#45]

**Comment by Benbiubiu** [comment]
大佬 我又来了哈哈哈，请您指点一下

**Comment by Benbiubiu** [comment]
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/1fe1de06-b555-4016-ad86-02f65be7bd2f">

**Comment by smthemex** [comment]
加载的图片数量不对，麻烦截图完整点，

**Comment by Benbiubiu** [comment]
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/065e830a-3a7d-4315-b10c-68bb6acd7209">

**Comment by smthemex** [comment]
双角色要用batch img 大佬 别搞我，自己看看readme

**Comment by Benbiubiu** [comment]
行了，感恩大佬

**Comment by Benbiubiu** [comment]
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/0feae174-368c-493c-99f6-885f60437e68">
大神我用playground有什么要注意的吗，我出来的图是黑色的

**Comment by smthemex** [comment]
这个的vae要单独设置，下次更新再改了

**Comment by Benbiubiu** [comment]
好的 谢谢
