### ISSUE TITLE
图生图的bug report

### ISSUE THREAD

**Issue by T8star1984** [smthemex/ComfyUI_StoryDiffusion#5]
复制文生图一样的设置，角色ID设置2个

只上传一个参考图提示
Error occurred when executing Storydiffusion_Img2Img:

'[Bob]'

通过图像批次上传2个参考图，提示
Error occurred when executing Storydiffusion_Img2Img:

Too many dimensions: 4 > 3.

**Comment by smthemex** [comment]
批次上传双角色暂时没支持，如果是官方的gradio是可以支持的，这个我还没有做双角色，主要是comfyUI的批次图片要重新分出来，或者单独做个节点，等我下次更新吧。
