### ISSUE TITLE
输入[NC]就报错

### ISSUE THREAD

**Issue by Royrychou** [smthemex/ComfyUI_StoryDiffusion#51]
![QQ20240809-093947](https://github.com/user-attachments/assets/a7ec5eb2-2566-4efa-bdaa-06d2f34fb53e)

**Comment by smthemex** [comment]
双角色要各自有2个行场景描写才能用NC，单角色要1行

**Comment by Royrychou** [comment]
> 双角色要各自有2个行场景描写才能用NC，单角色要1行

后来发现了
