### ISSUE TITLE
你好，这次更新后出现了报错

### ISSUE THREAD

**Issue by T8mars** [smthemex/ComfyUI_StoryDiffusion#52]
![image](https://github.com/user-attachments/assets/0f87c684-22a4-48c1-a7ad-8722f319ba9c)
diffusers是0.27.2 之前一直是好的

**Comment by smthemex** [comment]
因为调用了kolors，它需要diffusers0.30以上版本，我修改一下，如果不用就不调用吧。

**Comment by T8mars** [comment]
好的谢谢
