### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by Mis-tian** [smthemex/ComfyUI_StoryDiffusion#54]
![image](https://github.com/user-attachments/assets/966ff135-d57c-413a-ad82-3675b2ed580c)

如图 在custom_nodes 目录clone 成功后提示 IMPORT FAILED

**Comment by smthemex** [comment]
你这是多旧的工作流了，用example里的新工作流

**Comment by Mis-tian** [comment]
用的是https://github.com/smthemex/ComfyUI_StoryDiffusion/blob/main/examples/newtxt2img.json
貌似看起来是node 的安装没成功 导入插件失败了·~ 如果是工作流问题我去examples中换一个试试

**Comment by Mis-tian** [comment]
> 你这是多旧的工作流了，用example里的新工作流

我换新工作流一样~，我新建节点没找到StoryDiffusion ，是插件没安装成功。我comfyUI是新版本呢

**Comment by smthemex** [comment]
新版本多了很多需求库，你要看下缺少哪个才行

**Comment by Mis-tian** [comment]
> 新版本多了很多需求库，你要看下缺少哪个才行

按依赖列表 一来我都安装了，咋还有漏的~
确实观察到一些依赖安装问题，一开始是insightface 没装，这会儿又报这个了~ 

![image](https://github.com/user-attachments/assets/d723af7c-f2c7-4218-8d56-1bfb77069ef3)

**Comment by ericxl277** [comment]
和你的安装经历类似，用的是comfyui官方的windows整合包，clone完项目安装依赖之后，运行comfui报错，提示缺少opencv的库，装了之后又说没有cpython，接着就是insightface。insightface 安装开始用清华源安装也报错，换成官方默认源安装才算安好。希望这些对你解决问题有点帮助。 我之前已经安装成功了，也成功跑通example里的流程了，但最近又装了2个新插件，就是comfyui-manager和ComfyUI-Crystools，更新了下comfyui，然后就运行报错了。。。。不知道到底是插件冲突还是升级带来的问题。折腾了很久才又装上了。。。。。
