### ISSUE TITLE
没有名为“diffusers.callbacks”的模块

### ISSUE THREAD

**Issue by nishili** [smthemex/ComfyUI_StoryDiffusion#55]
用的V2，出现了这个情况？
![屏幕截图_20-8-2024_174144_127 0 0 1](https://github.com/user-attachments/assets/296e512f-5f46-4e6b-8980-d7da01547fd4)

**Comment by nishili** [comment]
你好，用的V1是这情况。
![屏幕截图_20-8-2024_204330_127 0 0 1](https://github.com/user-attachments/assets/3eb11aa4-c3a4-40e3-83e0-699d0324bbba)

**Comment by smthemex** [comment]
换个模型，不行就升级一下diffusers的版本
