### ISSUE TITLE
Error no file named scheduler_config.json found in directory 

### ISSUE THREAD

**Issue by Smirk-CAF** [smthemex/ComfyUI_StoryDiffusion#64]
![1725353584804](https://github.com/user-attachments/assets/a05785ea-864f-4195-9a9d-06afe1d09a03)
![image](https://github.com/user-attachments/assets/14acd8ee-6506-4c62-9020-113a3e824324)
Hello, I downloaded my own model into this directory, running after the error, did not help me to create transformer fp8.pt in checkpoints
您好，我自己下载的模型放到了该目录，运行后报错，没有在checkpoints内帮我创建transformer的fp8.pt

**Comment by smthemex** [comment]
flux去玩comfyUI自带的就好，我这是在试pipeline流程。  repo要填写完整的模型文件，不是单一个，而是很多。以下是示例需要的文件夹和文件：
![image](https://github.com/user-attachments/assets/f2059b64-1a89-48e7-936c-875896415a0e)

**Comment by Smirk-CAF** [comment]
谢谢，您的意思是我可以不用你的节点，只用comfyui自带的也能利用flux 实现生成的多张图片保持一致性？

> flux去玩comfyUI自带的就好，我这是在试pipeline流程。repo要填写完整的模型文件，不是单一个，而是很多。以下是示例需要的文件夹和文件： ![image](https://private-user-images.githubusercontent.com/138738845/363981123-f2059b64-1a89-48e7-936c-875896415a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTQyNDYsIm5iZiI6MTcyNTQxMzk0NiwicGF0aCI6Ii8xMzg3Mzg4NDUvMzYzOTgxMTIzLWYyMDU5YjY0LTFhODktNDhlNy05MzZjLTg3NTg5NjQxNWEwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwMTM5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzY2MDUxODYyOWIzYmQ4ODVkMmRhOGMwN2FkOTU4NTY1YmU4MzhlM2NhYmY1YWU2MDA2N2Y3ZjU5OWVlNGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3hUEdJBWEVUqm--ruPLTu4xViM387e6w_y9uOjsbvPM)
