### ISSUE TITLE
无法返回多张原图

### ISSUE THREAD

**Issue by Osming** [smthemex/ComfyUI_StoryDiffusion#7]
无论选择什么输出模式，都只能返回第一张图片，其他图片都不返回

**Comment by smthemex** [comment]
可能你的版本不是最新的，我更新了插件，应该是可以出多张图片的。

**Comment by Osming** [comment]
> 可能你的版本不是最新的，我更新了插件，应该是可以出多张图片的。

看到最新版本已经可以了
