### ISSUE TITLE
用nf4这个wokerflow报错

### ISSUE THREAD

**Issue by yishuaidu** [smthemex/ComfyUI_StoryDiffusion#70]
![image](https://github.com/user-attachments/assets/7df25a21-0120-4f8a-833e-ec0c6557804f)
![image](https://github.com/user-attachments/assets/666ba767-e0c0-44fc-afbd-ab2c9938e615)
![Uploading image.png…]()

大佬help

**Comment by wangxian** [comment]
你另一张图，上传失败了

repo_id 是完整的 flux-dev 路径，例如：/home/ai/code/ComfyUI_latest/models/diffusers/black-forest-labs/FLUX.1-dev

ave_id: flux_ae.sft 选择一下试试

**Comment by yishuaidu** [comment]
> 你另一张图，上传失败了
> 
> repo_id 是完整的 flux-dev 路径，例如：/home/ai/code/ComfyUI_latest/models/diffusers/black-forest-labs/FLUX.1-dev
> 
> ave_id: flux_ae.sft 选择一下试试

![image](https://github.com/user-attachments/assets/8aebc9dc-e5e3-44c8-8a58-ad829eb7ed5b)
repo_id ： C:\Users\Administrator\Desktop\flux\black-forest-labs\FLUX.1-dev

他报上图这个错误

**Comment by smthemex** [comment]
black-forest-labs\FLUX.1-dev 必须是包括所有文件，除了我打叉的2个模型
![image](https://github.com/user-attachments/assets/e65cf017-889d-4a19-b451-9b6a5de07c7a)

**Comment by yishuaidu** [comment]
> black-forest-labs\FLUX.1-dev 必须是包括所有文件，除了我打叉的2个模型 ![image](https://private-user-images.githubusercontent.com/138738845/367177915-e65cf017-889d-4a19-b451-9b6a5de07c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTIzMDAsIm5iZiI6MTcyNjIxMjAwMCwicGF0aCI6Ii8xMzg3Mzg4NDUvMzY3MTc3OTE1LWU2NWNmMDE3LTg4OWQtNGExOS1iNDUxLTliNmE1ZGUwN2M3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwNzIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ2Y2FiYTc5YThjNGRiMTU1NWM5ZTliNGU4NjQ5MGNiNmYyODVkMTRmMGMzNzVlZWRkNzY0NTVjNzBmMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-uupcTcsQaLyX9BDug65-Z7oH1TBHYr3qEs-yhMzmqs)

感谢回复，我已经解决拉。。 我另外想问个问题，我看你代码 貌似在use flux 没有用set_attention_processor， 他的一致性是另外的方法吗？还是我看错了

**Comment by smthemex** [comment]
> > black-forest-labs\FLUX.1-dev 必须是包括所有文件，除了我打叉的2个模型 ![image](https://private-user-images.githubusercontent.com/138738845/367177915-e65cf017-889d-4a19-b451-9b6a5de07c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTIzMDAsIm5iZiI6MTcyNjIxMjAwMCwicGF0aCI6Ii8xMzg3Mzg4NDUvMzY3MTc3OTE1LWU2NWNmMDE3LTg4OWQtNGExOS1iNDUxLTliNmE1ZGUwN2M3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwNzIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ2Y2FiYTc5YThjNGRiMTU1NWM5ZTliNGU4NjQ5MGNiNmYyODVkMTRmMGMzNzVlZWRkNzY0NTVjNzBmMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-uupcTcsQaLyX9BDug65-Z7oH1TBHYr3qEs-yhMzmqs)
> 
> 感谢回复，我已经解决拉。。 我另外想问个问题，我看你代码 貌似在use flux 没有用set_attention_processor， 他的一致性是另外的方法吗？还是我看错了

都不是同一类模型了，没法用set_attention_processor，一致性通过其他方法来尝试实现

**Comment by yishuaidu** [comment]
> > > black-forest-labs\FLUX.1-dev 必须是包括所有文件，除了我打叉的2个模型 ![image](https://private-user-images.githubusercontent.com/138738845/367177915-e65cf017-889d-4a19-b451-9b6a5de07c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTIzMDAsIm5iZiI6MTcyNjIxMjAwMCwicGF0aCI6Ii8xMzg3Mzg4NDUvMzY3MTc3OTE1LWU2NWNmMDE3LTg4OWQtNGExOS1iNDUxLTliNmE1ZGUwN2M3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwNzIwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ2Y2FiYTc5YThjNGRiMTU1NWM5ZTliNGU4NjQ5MGNiNmYyODVkMTRmMGMzNzVlZWRkNzY0NTVjNzBmMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-uupcTcsQaLyX9BDug65-Z7oH1TBHYr3qEs-yhMzmqs)
> > 
> > 
> > 感谢回复，我已经解决拉。。 我另外想问个问题，我看你代码 貌似在use flux 没有用set_attention_processor， 他的一致性是另外的方法吗？还是我看错了
> 
> 都不是同一类模型了，没法用set_attention_processor，一致性通过其他方法来尝试实现

ok 谢谢
