### ISSUE TITLE
PuLID_Flux does not get past the model loading phase.

### ISSUE THREAD

**Issue by JPW0080** [smthemex/ComfyUI_StoryDiffusion#72]
Right, so the entire black-forest-labs/FLUX.1-dev has been downloaded.
flux1-dev.safetensors was omitted.
pulid_flux_v0.9.0.safetensors was placed in /ComfyUI/models/photomaker
flux1-kj-dev-fp8.safetensors has also been downloaded and placed in /ComfyUI/models/checkpoints
When the flux_pulid_fp8_12GVR.png workflow has been recreated/executed, an error occurs.

Is exactly,
https://github.com/smthemex/ComfyUI_StoryDiffusion/issues/70

**Comment by smthemex** [comment]
try new version

**Comment by greengerong** [comment]
thanks, fixed

**Comment by JPW0080** [comment]
So it appears that the repo_id on the Storydiffusion_Model_Loader is case sensitive?

/ComfyUI/models/flux.1-dev = Error

/ComfyUI/models/FLUX.1-dev = Worked

https://github.com/smthemex/ComfyUI_StoryDiffusion/issues/73#issuecomment-2360386730
