### ISSUE TITLE
No module named 'ComfyUI_StoryDiffusion.PuLID.flux.transformer_flux'

### ISSUE THREAD

**Issue by greengerong** [smthemex/ComfyUI_StoryDiffusion#74]
How to solve this issue:

```
Prompt executed in 1.15 seconds
got prompt
!!! Exception during processing !!! No module named 'ComfyUI_StoryDiffusion.PuLID.flux.transformer_flux'
Traceback (most recent call last):
  File "/mnt/d/project/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/mnt/d/project/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/mnt/d/project/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/mnt/d/project/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/mnt/d/project/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1766, in story_model_loader
    from .PuLID.app_flux import FluxGenerator
  File "/mnt/d/project/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/PuLID/app_flux.py", line 7, in <module>
    from .flux.util import load_ae, load_clip, load_flow_model, load_t5, load_flow_model_quintized,SamplingOptions
  File "/mnt/d/project/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/PuLID/flux/util.py", line 5, in <module>
    from .transformer_flux import FluxTransformer2DModel
```
![image](https://github.com/user-attachments/assets/2419ae22-d7ba-407c-9fbe-3174a964ec06)

I had install new version diffusers : ``` pip install git+https://github.com/huggingface/diffusers.git```.

![image](https://github.com/user-attachments/assets/5403c9ae-9426-4250-8f9c-2a0e7df2ec4c)

**Comment by smthemex** [comment]
Yes, this error was left over from my testing of NF4. You can delete that line of code or update to the latest plugin,

**Comment by sunyiwk** [comment]
你的repo_id文件是什么结构 能看一下么

**Comment by greengerong** [comment]
> NF4.

thanks， this issue fixed。but it seem to 24G isn't enough, out of memory. Also tried the NF4 version.

**Comment by smthemex** [comment]
flux-pulid need more VRAM，but， nf4 maybe can try 10G or 8G...

**Comment by greengerong** [comment]
> flux-pulid need more VRAM，but， nf4 maybe can try 10G or 8G...

NF4 also  out of memory。 workflow ：
![image](https://github.com/user-attachments/assets/1c25f944-45f1-4052-9a9c-b89af1c1e4df)

**Comment by smthemex** [comment]
if using nf4，need fill nf4 in easy function，However, the PULID of NF4 can currently only generate noise, so it is not recommended to use it

**Comment by greengerong** [comment]
> if using nf4，need fill nf4 in easy function，However, the PULID of NF4 can currently only generate noise, so it is not recommended to use it

thanks
