### ISSUE TITLE
这是啥原因？

### ISSUE THREAD

**Issue by TAGYi12138** [smthemex/ComfyUI_StoryDiffusion#8]
![QQ图片20240604115958](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/168617651/abd4c3d2-de7d-4d95-b793-3c31f129a29e)

**Comment by smthemex** [comment]
看报错是torch_custom_ops模块无法导入，而需求这个的是torchvision，但是你的是Linux平台，而且用的是miniconda环境，所以你得在你的环境里，重新安装或者更新torchvision，torch，
