### ISSUE TITLE
太容易显存不够了

### ISSUE THREAD

**Issue by xueqing0622** [smthemex/ComfyUI_StoryDiffusion#83]
双人需要两个预先描述，也就是2*2=4，然后再一张双人，就5张图，
306012g显卡，太容易显存不够了
通常渲染跑完步数，最后出图就显存不够，能否查查问题在哪

**Comment by smthemex** [comment]
这个bug已经修复，图生图目前只需要2行描述词，3张图足够，而文生图需要预生成一张，所以还是需要5张图

**Comment by xueqing0622** [comment]
谢谢解答！
